#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LeftClawPot,    sensorPotentiometer)
#pragma config(Sensor, in2,    RightClawPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    LeftLine,       sensorLineFollower)
#pragma config(Sensor, in5,    RightLine,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  liftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rEnc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Ultra,          sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  RightBackDriveEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  LeftBackDriveEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  LeftMiddleLiftEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  RightMiddleLiftEnc, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftClaw,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TopLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftBottomLift, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port4,           LeftTopDrive,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RightTopDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RightBottomDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           LeftBottomDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           RightBottomLift, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           MiddleLift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightClaw,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#define I2C_TICKS_PER_REV_SPEED 392

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "functions.c"
#include "auton.c"
#include "lcd.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

	LCDInit(); //Turn on the LCD and initialize

	if( nVexRCReceiveState && vrCompetitionSwitch ) //Check if connected to comp switch
	{

		chooseAuton(); //Prompt to choose an autonomous routine

		//Clear encoder values
		SensorValue[ LeftBackDriveEnc ] = 0;
		SensorValue[ RightBackDriveEnc ] = 0;

		SensorValue( gyro ) = 0; //Reset gyro

		//Eliminate gyro drift
		SensorType(gyro) = sensorNone;
		wait1Msec( 500 );
		SensorType(gyro) = sensorGyro;

		wait1Msec(1500); //give time for gyro to init

	}

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	//Initialize tasks
	startTask( clawHold ); //Claw proportional control
	startTask( liftHold ); //Lift proportional control
	startTask( drivePControl ); //Drive proportional control

	//Run the control loops continuously
	doDriveP = true;
	doClawHold = true;
	doLiftHold = true;

	runLCDAuton(); //Run the auton that was picked earlier

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  //Start proportional control tasks for button positions
  startTask( clawHold );
  startTask( liftHold );

  while (true) //Run driver control checks continuously
  {

		driverClaw( ( vexRT[Btn6DXmtr2]*-127 + vexRT[Btn6UXmtr2]*127 + 10 ) ); //Send button values to claw, +10 to keep open against ruber bands
  	lift( vexRT[Btn5UXmtr2]*127 + vexRT[Btn5DXmtr2]*-50 + vexRT[Btn7DXmtr2]*-127 + 10 ); //Send button values to lift, +10 to keep lift up
		driverDrive( trueSpeed( vexRT[Ch3] ), trueSpeed( vexRT[Ch2] ) ); //Send TrueSpeed Joystick values to drive

  	wait1Msec( 25 ); //Sleep so other tasks can run simultaneously

  }
}
